Display errors only for changed code
humanmade/linter-bot pull request #153
Opened 2021-02-04 21:20 UTC by faishal

Related to https://github.com/humanmade/product-dev/issues/624

- Consider only `add` items from change
- Add comments in the review

2021-02-04 23:27 UTC, rmccue commented
Can we ensure these changes are behind env var flags too? The behaviour for hmlinter shouldn't change, only for altis-review, so we'll need to ensure they're variable in that regard.

2021-02-05 21:32 UTC, faishal commented
- When `CHECK_ANNOTATION_ONLY_RELATED` is not set : [run result](https://github.com/humanmade/altis-code-review/pull/5/checks?check_run_id=1841996120)

![image](https://user-images.githubusercontent.com/1633818/107091243-742e1380-67cf-11eb-89e9-d96ebdd6d831.png)

- When `CHECK_ANNOTATION_ONLY_RELATED` is set to `1` : [run result](https://github.com/humanmade/altis-code-review/pull/5/checks?check_run_id=1841998474) 

![image](https://user-images.githubusercontent.com/1633818/107091299-8e67f180-67cf-11eb-965e-a8959ee6f85e.png)

2021-02-08 12:40 UTC, rmccue requested changes
It looks like this is still using the comment mode rather than the annotation mode?

2021-02-08 12:40 UTC, rmccue commented on src/diff.js
> +				if( change.type === "add" ) {
```suggestion
				if ( change.type === "add" ) {
```

What about for removals? 🤔

2021-02-08 12:40 UTC, rmccue commented on src/format.js
> +			if( process.env.CHECK_ANNOTATION_ONLY_RELATED ){
```suggestion
			if ( process.env.CHECK_ANNOTATION_ONLY_RELATED ){
```

2021-02-08 12:40 UTC, rmccue commented on src/hooks.js
> +		 event
Invalid indentation here.

```suggestion
		comments,
		event
```

2021-02-08 12:40 UTC, rmccue commented on src/hooks.js
> +		// commit_id: commit,
Why is this removed?

2021-02-09 18:37 UTC, faishal commented on src/diff.js
> +				if( change.type === "add" ) {
we don't have to review the code that has been removed in terms of security/ performance issues.

2021-02-09 18:51 UTC, rmccue commented on src/diff.js
> +				if( change.type === "add" ) {
Hmm, true; I thought it might screw up the offsetting or not work for changes, but seems fine.

2021-02-10 16:55 UTC, rmccue approved these changes

2021-02-10 19:17 UTC, merged