Allow option change tmp directory
humanmade/linter-bot pull request #157
Opened 2021-06-15 23:04 UTC by faishal

- Added env variable to change defualt `/tmp` location.

2021-06-22 16:10 UTC, rmccue commented on src/index.js
>  const withClean = func => ( ...args ) => func( ...args ).then( () => clean() );
```suggestion
const withClean = func => ( ...args ) => func( ...args ).finally( () => clean() );
```

2021-09-09 09:44 UTC, rmccue commented on src/hooks.js
> +		( { id, head_branch, head_sha, pull_requests } = payload.check_suite || payload.check_run.check_suite );
Not sure why you've got bonus parens around these, is that required for the syntax?

2021-09-09 09:46 UTC, rmccue requested changes

2021-09-09 09:46 UTC, rmccue commented on src/hooks.js
> +	} else if( payload.pull_request ) {
```suggestion
	} else if ( payload.pull_request ) {
```

2021-09-09 09:46 UTC, rmccue commented on src/hooks.js
> +	}
What if none of these match? Need an `else` to fail here.

2021-09-09 09:46 UTC, rmccue commented on src/index.js
> +	} else if ( payload.check_run && payload.check_run.check_suite ){
```suggestion
	} else if ( payload.check_run && payload.check_run.check_suite ) {
```

2021-09-09 09:46 UTC, rmccue commented on src/index.js
> +	} else if( payload.pull_request ){
```suggestion
	} else if ( payload.pull_request ) {
```

2021-09-09 09:46 UTC, rmccue commented on src/index.js
> +	}
Needs an `else` here too.

2021-09-09 20:10 UTC, faishal commented on src/hooks.js
> +		( { id, head_branch, head_sha, pull_requests } = payload.check_suite || payload.check_run.check_suite );
Yes - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#syntax

Considering I have declared variable early

2021-09-15 16:28 UTC, kadamwhite approved these changes
Changes have been addressed and this has been deployed and tested as part of an Altis-side bot, so merging away

2021-09-15 16:28 UTC, merged